In [1]:
import pandas as pd
import numpy as np
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
file_path = "/kaggle/input/datasets/shanuka5668/tamilds1/Emotion_Analysis_Task_A_train_with_headers.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (14208, 2)

   Emotion                                               Text
0  Neutral              நாளைக்கு அரிசிக்கு இந்த நிலமை வந்தா 🙂
1    Anger                               மானம் கேட்ட அன்புமணி
2  Neutral  தவறு இஸ்ரேல் இருக்காது இதை நான் கூறவில்லை ஹமாஸ...
3      Joy  கொங்கு நாட்டு சிங்கம் உன்மையும் நேர்மையும் உலை...
4  Neutral  இவர் யார்? ஒவ்வொரு வார்த்தையும் முன்னுக்கு பின...

In [3]:
print(df.columns)

Index(['Emotion', 'Text'], dtype='object')

In [4]:
df.dropna(inplace=True)

print("After removing missing values:", df.shape)

After removing missing values: (14208, 2)

In [5]:
def clean_text(text):
    text = str(text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove mentions
    text = re.sub(r"@\w+", "", text)

    # Remove hashtags symbol only
    text = re.sub(r"#", "", text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    # Lowercase
    text = text.lower()

    return text

In [6]:
df["Clean_Text"] = df["Text"].apply(clean_text)

df.head()

,Emotion,Text,Clean_Text
0,Neutral,நாளைக்கு அரிசிக்கு இந்த நிலமை வந்தா 🙂,நாளைக்கு அரிசிக்கு இந்த நிலமை வந்தா 🙂
1,Anger,மானம் கேட்ட அன்புமணி,மானம் கேட்ட அன்புமணி
2,Neutral,தவறு இஸ்ரேல் இருக்காது இதை நான் கூறவில்லை ஹமாஸ...,தவறு இஸ்ரேல் இருக்காது இதை நான் கூறவில்லை ஹமாஸ...
3,Joy,கொங்கு நாட்டு சிங்கம் உன்மையும் நேர்மையும் உலை...,கொங்கு நாட்டு சிங்கம் உன்மையும் நேர்மையும் உலை...
4,Neutral,இவர் யார்? ஒவ்வொரு வார்த்தையும் முன்னுக்கு பின...,இவர் யார் ஒவ்வொரு வார்த்தையும் முன்னுக்கு பின்...

In [7]:
label_encoder = LabelEncoder()

df["Label"] = label_encoder.fit_transform(df["Emotion"])

print("Emotion Classes:")
print(label_encoder.classes_)

Emotion Classes:
['Ambiguous' 'Anger' 'Anticipation' 'Disguist' 'Fear' 'Joy' 'Love'
 'Neutral' 'Sadness' 'Surprise' 'Trust']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    df["Clean_Text"],
    df["Label"],
    test_size=0.2,
    random_state=42,
    stratify=df["Label"]
)

print("Train size:", len(X_train))
print("Test size:", len(X_test))

Train size: 11366
Test size: 2842

In [9]:
df.to_csv("cleaned_emotion_dataset.csv", index=False)